# fly.toml file generated for myveryownpokedex on 2023-04-13T15:00:14+02:00

app = "myveryownpokedex"
primary_region = "cdg"

[env]
  PORT = "8080"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.1"

[[services]]
  internal_port = 8080
  processes = ["app"]

[[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"

[[services.http_checks]]
  interval = 10000
  grace_period = "5s"
  method = "get"
  path = "/"
  protocol = "http"
  restart_limit = 0
  timeout = 2000
  tls_skip_verify = false
  [services.http_checks.headers]

[checks]
  [checks.version_check]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/version"
    port = 5500
    timeout = "10s"
    type = "http"
  [checks.health_check]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/health"
    port = 5500
    timeout = "10s"
    type = "http"