# fly.toml file generated for myveryownpokedex on 2023-04-13T15:00:14+02:00

app = "myveryownpokedex"
primary_region = "cdg"

[env]
  PORT = "5001"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.0"

[[services]]
  internal_port = 5001
  processes = ["app"]

[[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"